######################################################################
# Automatically generated by qmake (2.01a) wt. lis 23 13:04:10 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . app include
INCLUDEPATH += . include
DEFINES += VIEWER

# Input
HEADERS += include/mainwindow.h
SOURCES += app/main.cpp app/mainwindow.cpp

FORMS += \
    app/viewerwindow.ui

TRANSLATIONS = lang/qute_viewer_pl.ts
CODECFORTR = UTF-8
