######################################################################
# Automatically generated by qmake (2.01a) wt. lis 23 12:38:08 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . app include src
INCLUDEPATH += . include

# Input
HEADERS += include/mainwindow.h include/renderarea.h
SOURCES += app/main.cpp app/mainwindow.cpp src/renderarea.cpp

FORMS += \
    app/mainwindow.ui
